name: Lint
on:
  push:
  pull_request:
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install ruff
      - name: Ruff lint
        run: ruff check .
      - name: Ruff format (check only)
        run: ruff format --check .
